export const KEYWORDS = [
  'AI',
  'LLM',
  'GPT',
  'OpenAI',
  'Anthropic',
  'Gemini',
  'Mistral',
  'RAG',
  'Agent',
  'Fine-tuning',
  'Inference',
  'Sora',
  'Multimodal',
  'Tool use',
  'Alignment',
];

export const KEYWORD_SYNONYMS: Record<string, string[]> = {
  AI: ['artificial intelligence', '인공지능'],
  LLM: ['large language model', 'large language models', 'llms', '대규모 언어 모델', '거대 언어 모델'],
  GPT: ['chatgpt', 'chat gpt', 'gpt-4', 'gpt4', 'gpt-4o', 'gpt-4.1', 'gpt-3.5'],
  OpenAI: ['open ai', 'openai'],
  Anthropic: ['claude', 'anthropic'],
  Gemini: ['google gemini', 'gemini'],
  Mistral: ['mistral ai', 'mistral'],
  RAG: [
    'retrieval augmented generation',
    'retrieval-augmented generation',
    '검색 증강',
    '검색 증강 생성',
  ],
  Agent: ['agentic', 'multi-agent', '에이전트'],
  'Fine-tuning': ['fine tuning', 'finetuning', '파인튜닝', '파인 튜닝'],
  Inference: ['inference time', 'inference-time', '추론', '추론 시간'],
  Sora: ['sora'],
  Multimodal: ['multi modal', 'multi-modal', '멀티모달'],
  'Tool use': ['tool use', 'tool-use', 'function calling', 'function-calling', '툴 사용', '도구 사용'],
  Alignment: ['alignment', 'ai safety', '안전', '안전성', '정렬'],
};

export const KEYWORD_LABELS_KO: Record<string, string> = {
  AI: 'AI',
  LLM: 'LLM',
  GPT: 'GPT',
  OpenAI: 'OpenAI',
  Anthropic: 'Anthropic',
  Gemini: 'Gemini',
  Mistral: 'Mistral',
  RAG: 'RAG',
  Agent: '에이전트',
  'Fine-tuning': '파인튜닝',
  Inference: '추론',
  Sora: 'Sora',
  Multimodal: '멀티모달',
  'Tool use': '툴 사용',
  Alignment: '정렬/안전성',
};
